# SSH shortcuts
alias tower="ssh root@10.128.0.100"
alias app-host="ssh skippythesnake@10.128.0.115"

# Navigate to windows drives
alias c="cd /mnt/c/"
alias d="cd /mnt/d/"
alias e="cd /mnt/e/"
alias f="cd /mnt/f/"

# Open windows explorer at current location
alias explore='explorer.exe .'